/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DefaultLayout: typeof import('./src/layouts/defaultLayout.vue')['default']
    Drag: typeof import('./src/components/Drag.vue')['default']
    ElementTree: typeof import('./src/components/ElementTree.vue')['default']
    GridEdge: typeof import('./src/components/GridEdge.vue')['default']
    HelloWorld: typeof import('./src/pages/HelloWorld.vue')['default']
    Home: typeof import('./src/views/home/Home.vue')['default']
    HomeView: typeof import('./src/views/home/HomeView.vue')['default']
    JsEdge: typeof import('./src/components/JsEdge.vue')['default']
    Login: typeof import('./src/views/login/Login.vue')['default']
    LoginView: typeof import('./src/views/login/LoginView.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sea: typeof import('./src/components/Sea.vue')['default']
    Selector: typeof import('./src/components/Selector.vue')['default']
    WorkBench: typeof import('./src/views/workBench/WorkBench.vue')['default']
    WorkBenchView: typeof import('./src/views/workBench/WorkBenchView.vue')['default']
  }
}
